SUBDIR := keystone-rt

KEYSTONE_PLATFORM ?= hifive_unmatched

.PHONY: all
all:
	$(MAKE) -C $(SUBDIR) KEYSTONE_PLATFORM=$(KEYSTONE_PLATFORM)

%:
	$(MAKE) -C $(SUBDIR) $@ KEYSTONE_PLATFORM=$(KEYSTONE_PLATFORM)